### ISSUE TITLE
Missing Doctrine

### ISSUE THREAD

**Issue by loevstroem** [lyrixx/Silex-Kitchen-Edition#22]
Hi,

By following the install guidelines provided, my installation ends up missing Doctrine :- (

git clone https://github.com/lyrixx/Silex-Kitchen-Edition.git PATH/TO/YOUR/APP
cd PATH/TO/YOUR/APP
curl -s http://getcomposer.org/installer | php
php composer.phar install

Manually adding "doctrine/dbal": ">=2.2.0,<2.4.0-dev" to the composer file and updating, downloads the library. Afterwards continuing and follow Silex Doctrine guide, I add a database connection in app.php.

$app->register(new Silex\Provider\DoctrineServiceProvider(), array(
    'db.options' => array(
        'driver' => 'pdo_mysql',
        'host' => 'localhost',
        'dbname'    => 'test',
        'user'  => 'test',
        'password'  => ''
    )
));

However this attempt brings:

Fatal error: Class 'Doctrine\DBAL\Configuration' not found in /home/www/*/vendor/silex/silex/src/Silex/Provider/DoctrineServiceProvider.php on line 86

Currently I'm unable to connect to any database using Silex Kitchen Edition.

If this is considered no real issue, or is because of errors on my end I apologize :)

Thanks

**Comment by stefan16111** [comment]
Still helpful in 2017 :)
