### ISSUE TITLE
doctrine:database:create unset dbname than miss after for mysli connection

### ISSUE THREAD

**Issue by gagarine** [lyrixx/Silex-Kitchen-Edition#50]
I get a

   Notice: Undefined index: dbname in vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php on line 41

**Comment by lyrixx** [comment]
Sorry for this long long delay. It looks like the notice come from vendored code ; So I'm closing this issue.
