### ISSUE TITLE
WebDebugToolbarListener Exception after running composer update

### ISSUE THREAD

**Issue by locovich** [lyrixx/Silex-Kitchen-Edition#55]
Hello,

I've just run composer update, which updated several components, and now the WebDebugToolbar is throwing an exception.

Here is the list of updates composer did:
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing twig/twig (v1.14.2)
  - Installing twig/twig (v1.15.0)
    Downloading: 100%

  - Removing symfony/intl (v2.3.7)
  - Installing symfony/intl (v2.4.0)
    Downloading: 100%

  - Removing symfony/filesystem (v2.3.7)
  - Installing symfony/filesystem (v2.4.0)
    Downloading: 100%

  - Removing symfony/config (v2.3.7)
  - Installing symfony/config (v2.4.0)
    Downloading: 100%

  - Removing symfony/console (v2.3.7)
  - Installing symfony/console (v2.4.0)
    Downloading: 100%

  - Removing symfony/property-access (v2.3.7)
  - Installing symfony/property-access (v2.4.0)
    Downloading: 100%

  - Removing symfony/options-resolver (v2.3.7)
  - Installing symfony/options-resolver (v2.4.0)
    Downloading: 100%

  - Removing symfony/form (v2.3.7)
  - Installing symfony/form (v2.4.0)
    Downloading: 100%

  - Removing symfony/finder (v2.3.7)
  - Installing symfony/finder (v2.4.0)
    Downloading: 100%

  - Removing symfony/translation (v2.3.7)
  - Installing symfony/translation (v2.4.0)
    Downloading: 100%

  - Removing symfony/validator (v2.3.7)
  - Installing symfony/validator (v2.4.0)
    Downloading: 100%

  - Removing symfony/yaml (v2.3.7)
  - Installing symfony/yaml (v2.4.0)
    Downloading: 100%

  - Removing symfony/dom-crawler (v2.3.7)
  - Installing symfony/dom-crawler (v2.4.0)
    Downloading: 100%

  - Removing symfony/browser-kit (v2.3.7)
  - Installing symfony/browser-kit (v2.4.0)
    Downloading: 100%

  - Removing symfony/css-selector (v2.3.7)
  - Installing symfony/css-selector (v2.4.0)
    Downloading: 100%

  - Removing symfony/stopwatch (v2.3.7)
  - Installing symfony/stopwatch (v2.4.0)
    Downloading: 100%

  - Installing symfony/security-core (v2.4.0)
    Downloading: 100%

  - Removing symfony/debug (v2.3.7)
  - Installing symfony/debug (v2.4.0)
    Downloading: 100%

  - Installing symfony/security-csrf (v2.4.0)
    Downloading: 100%

  - Removing symfony/twig-bridge (v2.3.7)
  - Installing symfony/twig-bridge (v2.4.0)
    Downloading: 100%

  - Removing symfony/web-profiler-bundle (v2.3.7)
  - Installing symfony/web-profiler-bundle (v2.4.0)
    Downloading: 100%

And here is the Exception detail in my deveropment environment:

Whoops, looks like something went wrong.
1/1 FatalErrorException: Error: Call to undefined method Symfony\Component\HttpKernel\Event\FilterResponseEvent::isMasterRequest() in C:\Users\xxx\wc\Silex-Kitchen-Edition\vendor\symfony\web-profiler-bundle\Symfony\Bundle\WebProfilerBundle\EventListener\WebDebugToolbarListener.php line 68

    in C:\Users\xxx\wc\Silex-Kitchen-Edition\vendor\symfony\web-profiler-bundle\Symfony\Bundle\WebProfilerBundle\EventListener\WebDebugToolbarListener.php line 68
    at ErrorHandler->handleFatalError(object(ExceptionHandler), array('type' => '1', 'message' => 'Call to undefined method Symfony\Component\HttpKernel\Event\FilterResponseEvent::isMasterRequest()', 'file' => 'C:\Users\xxx\wc\Silex-Kitchen-Edition\vendor\symfony\web-profiler-bundle\Symfony\Bundle\WebProfilerBundle\EventListener\WebDebugToolbarListener.php', 'line' => '68')) in C:\Users\xxx\wc\Silex-Kitchen-Edition\vendor\symfony\debug\Symfony\Component\Debug\ErrorHandler.php line 212

Let me know if this should be reported directly in the Silex proyect.

Thanks!

**Comment by lyrixx** [comment]
Fixed by #62 (The profile is now gone ; Will re-add it later)
