### ISSUE TITLE
Update Kitchen Edition

### ISSUE THREAD

**Issue by webslash** [lyrixx/Silex-Kitchen-Edition#59]
Hi @lyrixx 

Thanks for providing this Silex kitchen Edition project, it's been very helpfull to get started with Silex!
Would it be possible to give this project an update?

This runs on 1.1, while there is now Silex 1.3. Bootstrap is still the older version.. I noticed the other issue about it from a year ago.. yet nothing has changed. 
Also including Swift Mailer would be very usefull, since basically every website needs an email form somewhere.

I found this to be by far the best starter project for Silex, so would love to see it being maintained.

Thanks!

**Comment by lyrixx** [comment]
Fixed by #62
