### ISSUE TITLE
Twig_Error_Syntax: Unknown "render" function in "@WebProfiler/Profiler/layout.html.twig"

### ISSUE THREAD

**Issue by bantar** [lyrixx/Silex-Kitchen-Edition#61]
Fresh install of Kitchen-Edition.  It throws the following error:

Twig_Error_Syntax in ExpressionParser.php line 573: Unknown "render" function in "@WebProfiler/Profiler/layout.html.twig" at line 67.

I did a bit of research and found the following suggestion for the problem:  [GitHub Comment regarding silexphp/Silex-WebProfiler] (https://github.com/silexphp/Silex-WebProfiler/issues/67#issuecomment-109202793)

After adding the following line to both index.php and index_dev.php, before $app->run(),  we're working again:
```
$app->register(new Silex\Provider\HttpFragmentServiceProvider());
```

**Comment by lyrixx** [comment]
Fixed by #62 (The profile is now gone ; Will re-add it later)

**Comment by tixastronauta** [comment]
@lyrixx any idea why `WebProfilerServiceProvider` is raising that error?

**Comment by lyrixx** [comment]
Nope, Sorry :/
